version: '2.4'
services:
  postgres: &postgres
    image: ${IMAGE_NAME-postgres-patroni}:${IMAGE_TAG-13.3-buster-2.1.4}
    build:
      context: .
      args:
        PG_BASE_IMG: ${PG_BASE_IMG-13.3-buster}
        PATRONI_VERSION: ${PATRONI_VERSION-2.1.4}
    extra_hosts:
      - "pg1-srv:${PG1_HOST-127.0.0.0.1}"
      - "pg2-srv:${PG2_HOST-127.0.0.0.1}"
      - "pg3-srv:${PG3_HOST-127.0.0.0.1}"
      - "pg4-srv:${PG4_HOST-127.0.0.0.1}"
      - "pg5-srv:${PG5_HOST-127.0.0.0.1}"      
      - "backup-srv:${PGBACKREST_REPO_HOST-127.0.0.1}"
    user: 1001:1001
    ports:
     - 5432:5432
    volumes:
    - ./pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
    - ./postgres-data:/home/postgres/postgres-lab/postgres-data
    - ./pg-certs:/home/postgres/postgres-lab/pg-certs
    - ./certs2:/home/postgres/postgres-lab/certs2
  postgres-pgbackrest:
    <<: *postgres
    entrypoint:
    - /usr/bin/pgbackrest
    - server
    ports:
     - 8432:8432
  postgres-pgbackrest-repository:
    <<: *postgres
    entrypoint:
    - /usr/bin/pgbackrest
    - server
    ports:
     - 8432:8432     