version: '2.4'
services:
  postgres: &postgres
    image: ${IMAGE_NAME-postgres-patroni}:${IMAGE_TAG-13.3-buster-2.1.4}
    build:
      context: .
      args:
        PG_BASE_IMG: ${PG_BASE_IMG-13.3-buster}
        PATRONI_VERSION: ${PATRONI_VERSION-2.1.4}
    extra_hosts:
      - "pg1-srv:${PG1_HOST-127.0.0.1}"
      - "pg2-srv:${PG2_HOST-127.0.0.1}"
      - "pg3-srv:${PG3_HOST-127.0.0.1}"
      - "pg4-srv:${PG4_HOST-127.0.0.1}"
      - "pg5-srv:${PG5_HOST-127.0.0.1}"      
      - "backup-srv:${PGBACKREST_REPO_HOST-127.0.1}"
    user: 1001:1001
    network_mode: host
    # ports:
    #  - 5432:5432
    #  - 8000:8000
    volumes:
    - ./patroni-config.yml:/home/postgres/patroni-config.yml:ro
    - ./postgres-data/data:${PG_DATA_PATH-/home/postgres/postgres-data/data}
    - ./postgres-data/logs:${PG_LOG_PATH-/home/postgres/postgres-data/logs}    
    - ./pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
    - ./pgbackrest-data/certs:${PGBACKREST_CERT_PATH-/home/postgres/pgbackrest-data/certs}
  # PG Backrest Server in each Postgres Host
  pgbackrest-postgres-server:
    <<: *postgres
    command:
    - /usr/bin/pgbackrest
    - server
    ports:
     - 8432:8432
  # PG Backrest Server in PG Backrest Repo Host
  pgbackrest-repo-server:
    <<: *postgres
    command:
    - /usr/bin/pgbackrest
    - server
    ports:
     - 8432:8432
    volumes:  
    - ./pgbackrest-data/backup_space:${PGBACKREST_BACKUP_SPACE_PATH-/home/postgres/pgbackrest-data/backup_space}